### ISSUE TITLE
Scanner detects all references to a.pomf.se or a.pomf.cat as virus signatures

### ISSUE THREAD

**Issue by ccd0** [oohnoitz/jii#15]
`a.pomf.se` is detected as `MBL_2827533.UNOFFICIAL`
`a.pomf.cat` is detected as `MBL_2961381.UNOFFICIAL`

**Comment by oohnoitz** [comment]
I'll mark this as `wontfix` since this isn't an issue with code. You'll need to contact the host/maintainer of the site that's using this software and have them tweak their virus signature databases for ClamAV.
