### ISSUE TITLE
text/plain is not kept when the extension is missing

### ISSUE THREAD

**Issue by RoxasShadow** [oohnoitz/jii#16]
If I try to upload a `text/plain` without extension, [this line](https://github.com/oohnoitz/jii/blob/543cfd473ec11aa589073f0601858bd0f48ddd8f/server/lib/storage/lib/gridfs.js#L108) replaces the its mime type to `application/octet-stream` since the lookup is performed on the file name.

This implies that I cannot read text files on jii but instead I need to download them before.

I actually wanted to open a PR, but then I thought that probably this is a feature rather than a bug.
What do you think?

**Comment by oohnoitz** [comment]
Yeah, it should actually fallback to `text/plain` in this case. This should be fixed in 72a62464e9fe7955fc43e62738733fe565f9fbd5.

**Comment by RoxasShadow** [comment]
It is, thanks you.
